Fix for running on CPU only systems
On my macbook and on the linux github actions CI, ``` pytest tests/unit/test_cpu_workflow.py```
fails with:

```
ERROR    nvtabular:workflow.py:366 Failed to transform operator <nvtabular.ops.categorify.Categorify object at 0x7fbed7cdc2b0>
Traceback (most recent call last):
  File "/Users/benf/code/nvtabular/nvtabular/ops/categorify.py", line 395, in transform
    new_df[name] = _encode(
  File "/Users/benf/code/nvtabular/nvtabular/ops/categorify.py", line 998, in _encode
    value = fetch_table_data(
  File "/Users/benf/code/nvtabular/nvtabular/worker.py", line 89, in fetch_table_data
    table = reader(f, **use_kwargs)
  File "/Users/benf/miniconda3/lib/python3.9/site-packages/pandas/io/parquet.py", line 459, in read_parquet
    return impl.read(
  File "/Users/benf/miniconda3/lib/python3.9/site-packages/pandas/io/parquet.py", line 221, in read
    return self.api.parquet.read_table(
  File "/Users/benf/miniconda3/lib/python3.9/site-packages/pyarrow/parquet.py", line 1700, in read_table
    dataset = _ParquetDatasetV2(
  File "/Users/benf/miniconda3/lib/python3.9/site-packages/pyarrow/parquet.py", line 1558, in __init__
    self._dataset = ds.dataset(path_or_paths, filesystem=filesystem,
  File "/Users/benf/miniconda3/lib/python3.9/site-packages/pyarrow/dataset.py", line 657, in dataset
    return _filesystem_dataset(source, **kwargs)
  File "/Users/benf/miniconda3/lib/python3.9/site-packages/pyarrow/dataset.py", line 402, in _filesystem_dataset
    fs, paths_or_selector = _ensure_single_source(source, filesystem)
  File "/Users/benf/miniconda3/lib/python3.9/site-packages/pyarrow/dataset.py", line 378, in _ensure_single_source
    raise FileNotFoundError(path)
FileNotFoundError: <fsspec.implementations.local.LocalFileOpener object at 0x7fbeb9a990d0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/benf/code/nvtabular/nvtabular/workflow.py", line 364, in _transform_partition
    df = column_group.op.transform(column_group.input_column_names, df)
  File "/Users/benf/code/nvtabular/nvtabular/dispatch.py", line 54, in inner2
    return func(*args, **kwargs)
  File "/Users/benf/code/nvtabular/nvtabular/ops/categorify.py", line 413, in transform
    raise RuntimeError(f"Failed to categorical encode column {name}") from e
RuntimeError: Failed to categorical encode column name-string
```

This seems to be a result of how fsspec.open interacts with pandas. When fsspec.open is called
as a context manager it returns a ```fsspec.implementations.local.LocalFileOpener``` object which
fails with pandas. However when not run as a context manager (just fsspec.open) it returns a
```fsspec.core.OpenFile``` object which works.

Work around this issue by not using the fsspec contextmanager, and use one from contextlib instead.

After this change I can run ``` pytest tests/unit/test_cpu_workflow.py``` on my macbook to test cpu
only capabalities.